version: '2'
services:
  airstrik-redis-service:
    container_name: airstrik-redis-service
    image: redis:5.0-rc3-alpine
    volumes:
      - ./data/redis/:/data
    ports:
      - 6379:6379

  airstrik-postgres:
    container_name: airstrik-postgres-service
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dockerpassword

  airstrik-access:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: airstrik/access
    container_name: access
    environment:
      ENV: "Local"
      _DB_DIALECT: "postgres"
      _DB_HOST: "account.cq02tlotebnu.ap-south-1.rds.amazonaws.com"
      _DB_PORT: "5432"
      _DB_USER: "postgres"
      _DB_PASSWORD: "dockerpassword"
      _REDIS_HOST : "greeny-redis-service:6379"
    ports:
      - 9001:9001
    volumes:
      - .:/app
      - ../gobase:/gobase
      - ./data/aws/:/root/.aws
    depends_on:
      - airstrik-postgres
      - airstrik-redis-service
    restart: always