version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data/ # persist data even if container shuts down

  mongo-service:
    container_name: mongo-service
    image: mongo:4.0.5
    volumes:
      - ./data/db/:/data/db
    ports:
      - 27017:27017
  # Production container. Builds in release mode and run. Project will be restarted on every abort.
  production:
    hostname: airstrike-production
    restart: always
    image: itsparser/airstrike
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      GIN_MODE: "release"     # Example ENV variable
      SERVING_PORT: "*:8080"  # Example ENV variable
    volumes:
      - .:/home/my-app
    working_dir: /home/my-app
    ports:
      - "8080:8080"  # Opened ports
    command: bash -c "go mod download && go build -o /bin/my-app . && /bin/my-app"

  # Development container. Runs in debug mode and live-reloading on every source file update.
  development:
    hostname: airstrike-development
    restart: always
    image: itsparser/airstrike
#    depends_on:
#      - mongo-service
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      DEBUG: "true"
      SERVING_PORT: ":8080"
    volumes:
      - .:/home/airstrike
    working_dir: /home/airstrike
    ports:
      - "8080:8080"
    command: bash -c "go mod download && make serve"